### ISSUE TITLE
Json file

### ISSUE THREAD

**Issue by alfa-dot** [Reynold29/CSI-Hymns-and-Lyrics#1]
How did you structure hymns_data json asset file

Thanks in advance

**Comment by Reynold29** [comment]
Sorry for the late reply, been busy a couple of weeks. Anyways, here's how it is structured:

https://github.com/Reynold29/CSI-Hymns-and-Lyrics/blob/665815f66bc00284f2880212bf3bd41609b85bf8/lib/assets/hymns_data.json

I removed it from this repo cuz I'll unify it in a different repo and make it easy to define in any future projects.

**Comment by alfa-dot** [comment]
Thanks a lot

**Comment by Reynold29** [comment]
You're Welcome. Since the issue is resolved, I'll be closing this issue. Feel free to reopen or create a new issue if anything arises. 👍
